server:
  port: 9897

spring:

  application:
    name: hms

  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10

    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create-drop